/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:bb99d60b-9ad3-4482-b552-ba74145fe9bd",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_RI29e0m18",
    "aws_user_pools_web_client_id": "4i8fak0ndp3r3p13ontqmp2s0d",
    "oauth": {}
};


export default awsmobile;
